### ISSUE TITLE
Upgrade packages based on threshold.

### ISSUE THREAD

**Issue by b4ux1t3** [dotnet-outdated/dotnet-outdated#143]
Between the `-u` and `-u:prompt` options, there seems to be space for an automated process to upgrade all packages if they are below a certain threshold of severity. For example, upgrade all packages if the upgrade is only a patch release, or only a minor release.

Essentially, we have a thin brush and a wide brush, but no medium sized brushes. 

Ideally, this would look something like this:

    dotnet outdated -u:minor

This would automatically upgrade all packages which have minor or patch releases, but not any major versions. 

    dotnet outdated -u:patch

This would only upgrade if it is a patch release, and leave any minor or major upgrades alone.

It would be nice to optionally prompt after this for any upgrades that aren't included under the threshold, but having to run the command again with `-u:prompt` isn't that big a deal.

**Comment by coderpatros** [comment]
Hi @b4ux1t3 I think you're after the `version-lock` option.

Your first example becomes `dotnet outdated -u -vl Major` and the second one becomes `dotnet outdated -u -vl Minor`

**Comment by b4ux1t3** [comment]
Aha! I should have read the `--help` more closely, it's right there. Thank you!
