### ISSUE TITLE
No code signature - breaks firewall

### ISSUE THREAD

**Issue by richardtallent** [dotnet-outdated/dotnet-outdated#157]
My Mac's firewall software is fairly picky, and it's not allowing outbound connections by `dotnet-outdated` since the executable isn't code-signed.

Unfortunately, this is the sort of thing that should only be set up by the developer who is pushing to nuget, or I'd look into submitting a PR to help :(.

**Comment by augustoproiete** [comment]
@richardtallent You could definitely help by sponsoring a code-signing certificate for signing dotnet-outdated. The cheapest cert I know of nowadays cost about 83 USD per year (from Comodo).

What do you think?

**Comment by richardtallent** [comment]
Ouch! I hadn't looked into the details before, but my Google-foo didn't lead to any better options. :(

Seems like a big glaring hole for viable open source applications.
