### ISSUE TITLE
Add .NET 6 Support 

### ISSUE THREAD

**Issue by solrevdev** [dotnet-outdated/dotnet-outdated#216]
on macOS, homebrew only leaves the latest SDK/runtime combo for .NET installed and so I was getting the following error when trying to run dotnet outdated

```text
▲ project [master] dotnet outdated -u:prompt
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' (x64) was not found.
  - The following frameworks were found:
      6.0.0 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=osx.11.0-x64
```

I've created a pull request that might fix this, please see pr #215

**Comment by timheuer** [comment]
As a part of this change, recommend removing 2.1 from TFM as that is now out of support.

**Comment by solrevdev** [comment]
> As a part of this change, recommend removing 2.1 from TFM as that is now out of support.

So to confirm @timheuer shall I remove `netcoreapp2.1` as a TFM option yes?

I’ll make any changes later this evening

**Comment by timheuer** [comment]
It's a final decision for the maintainers here, but 2.1 is officially out of support so I personally believe yes and TFMs should be netcoreapp3.1;net5.0;net6.0

**Comment by solrevdev** [comment]
Thanks @timheuer ill make the change to the PR a bit later I can always add back if maintainers change mind etc. 

Thanks again 🙏

**Comment by solrevdev** [comment]
Removed `netcoreapp2.1` from TFM...  [[commit](https://github.com/dotnet-outdated/dotnet-outdated/pull/215/commits/12818b8137533f4715ba5f40c49a1470dbbc2f69)]

**Comment by coderpatros** [comment]
Yep, agree with dropping 2.1. It's a breaking change, so I'll bump the major version.
