### ISSUE TITLE
`An error occurred while upgrading...` but no error message

### ISSUE THREAD

**Issue by TheRSP** [dotnet-outdated/dotnet-outdated#251]
When running this against some of my solutions I'm getting an error message:
```
An error occurred while upgrading [Project Name here]
```
There is not information to help me diagnose why I'm getting this error. Is it possible to log out `RunStatus.Output` to provide some hope of solving this?

Possibly, this could be behind a `--verbose` flag to prevent it littering the logs for everyone?

**Comment by jeffward01** [comment]
I also have this error, its strange, if I run:

````bash
> dotnet-outdated -u
````

I will receive that error 'alert', but no message or details.  Even when I output the results to a file, no error or issues are mentioned.

The strange part is if I upgrade or run a command like:

````bash
> dotnet add <project> package
````
the package will update without issue.

I am not able to update my project in some random cases with using `nukeeper` or `dotnet-outdated`, but if I run the standard `dotnet` command as I displayed above, it executes without issue.

**Comment by spaasis** [comment]
Same here - running the tool in Azure pipelines occasionally fails without error messages

**Comment by p1971** [comment]
Got a similar error message.
I uninstalled global and local, then reinstalled as local and it worked.

**Comment by specialforest** [comment]
For me the issue was coming from DotNetRunner having hardcoded 20 seconds timeout for adding a package (and restoring them):
https://github.com/dotnet-outdated/dotnet-outdated/blob/master/src/DotNetOutdated.Core/Services/DotNetRunner.cs#L36

As workaround could try "--no-restore" option.

**Comment by mechelewskim** [comment]
We're having the same issue occasionally when using the tool in our workflow in Github Actions and upgrading packages stored in Github Packages.

**Comment by mishioo** [comment]
I'm also experiencing this problem. I'm getting the `An error occurred while upgrading ...` notification for each package in my project. I'm keeping my `PackageReference`s in `Directory.Build.targets` file instead of `.csproj`, could that be the cause?

**Comment by reduckted** [comment]
I'm experiencing this as well. I have a very large solution and due to antivirus software that I'm unable to do anything about, a restore takes more than 20 seconds. That makes `dotnet-outdated` completely unusable for me. 😢

**Comment by DaveSenn** [comment]
I've the same problem. Running `dotnet outdated -u` results in the error `An error occurred while upgrading`:

``` 
> dotnet outdated -u
» Dal.Ado.Test
  [.NETFramework,Version=v7.0]
  Microsoft.NET.Test.Sdk  17.4.0 -> 17.4.1

» Dal.Ado
  [.NETFramework,Version=v7.0]
  Events    7.0.0.177  -> 7.1.0.180
  Interop   7.0.2.349  -> 7.1.0.352
  Utilities  7.2.16.170 -> 7.4.1.175

Version color legend:
<red>   : Major version update or pre-release version. Possible breaking changes.
<yellow>: Minor version update. Backwards-compatible features added.
<green> : Patch version update. Backwards-compatible bug fixes.

Upgrading package Microsoft.NET.Test.Sdk...
An error occurred while upgrading Dal.Ado.Test


Upgrading package Interop...
An error occurred while upgrading Dal.Ado


Upgrading package Utilities...
An error occurred while upgrading Dal.Ado


Upgrading package Events...
An error occurred while upgrading Dal.Ado
```


I then clone the repo (master) and tried to reproduce the issue with a debugger attached. But started from within VS it works... looks like this has been fixed?
```
» Dal.Ado.Test
  [net7.0]
  Microsoft.NET.Test.Sdk  17.4.0 -> 17.4.1

» Dal.Ado
  [net7.0]
  Events    7.0.0.177  -> 7.1.0.180
  Interop   7.0.2.349  -> 7.1.0.352
  Utilities  7.2.16.170 -> 7.4.1.175

Version color legend:
<red>   : Major version update or pre-release version. Possible breaking changes.
<yellow>: Minor version update. Backwards-compatible features added.
<green> : Patch version update. Backwards-compatible bug fixes.

Upgrading package Microsoft.NET.Test.Sdk...
Project Dal.Ado.Test [net7.0] upgraded successfully

Upgrading package Interop...
Project Dal.Ado [net7.0] upgraded successfully

Upgrading package Utilities...
Project Dal.Ado [net7.0] upgraded successfully

Upgrading package Events...
Project Dal.Ado [net7.0] upgraded successfully

Elapsed: 00:00:11.4814456
```

**Comment by Dunnymeister** [comment]
I setup dotnet outdated today on a build machine and ran into this issue. A configurable timeout would be solve this issue for us.

In the meantime I've started running `dotnet restore` prior to `dotnet outdated` to give it a chance to finish.

**Comment by reduckted** [comment]
I wonder if a `--no-restore` option would be easier to implement, rather than a configurable timeout. 🤔

**Comment by Dunnymeister** [comment]
Both options sound good, as long as the error messaging is updated to better communicate the error.

**Comment by reduckted** [comment]
@slang25 Do you have a preference between a configurable timeout vs a `--no-restore` option? #248 adds a configurable timeout. I'm happy to implement a `--no-restore` option if that's preferred.

**Comment by TheRSP** [comment]
A --no-restore argument would be fantastic

**Comment by reduckted** [comment]
I just realized that there's already a `--no-restore` option 🤦‍♂️. It's used for skipping package restore when updating packages.

I've come up with a different solution in #468. Rather than having a fixed timeout of 20 seconds for running the `dotnet` process, the timeout only applies from the time when output from the `dotnet` process was last received. So as long as the `dotnet` process is still writing something to stdout or stderr, `dotnet-outdated` will continue to wait for it to complete. If it doesn't output _anything_ for 20 seconds, then the process is aborted.

**Comment by timabell** [comment]
This issue isn't resolved for me

```
$ dotnet outdated --version                     
A .NET Core global tool to list outdated Nuget packages.
4.8.1+9730dd4f48fe1df7e30f35a0c6ed826107f4a547
```

```
$ dotnet outdated --version-lock Major --upgrade
Discovering projects...
Analyzing project(s)...
Analyzing dependencies...
» BackendAccountService.Api
  [net8.0]
  SonarAnalyzer.CSharp  9.30.0.95878 -> 9.32.0.97167

...

Upgrading package SonarAnalyzer.CSharp...
An error occurred while upgrading BackendAccountService.Api

An error occurred while upgrading BackendAccountService.Api.UnitTests

An error occurred while upgrading BackendAccountService.Core

...
```

The merged PR may have resolved one cause of errors, but this issue is asking for a `--verbose` that stops `dotnet-updated` from swallowing stdout/stderr from the underlying processes attempting (and failing) the package changes.

I vote to re-open.
