### ISSUE TITLE
Support central package management

### ISSUE THREAD

**Issue by WeihanLi** [dotnet-outdated/dotnet-outdated#281]
Currently, does not support the  central package management feature <https://docs.microsoft.com/en-us/nuget/consume-packages/central-package-management>

When I try to upgrade my packages, it did not update the package version defined in `Directory.Packages.props`, but updated the package in the project with a new version

![image](https://user-images.githubusercontent.com/7604648/164981881-8c277228-2731-458d-9f8f-e2d62219ecf4.png)

My project is here: https://github.com/WeihanLi/dotnet-httpie/tree/1898489d23a36b0764961e02e5a14929895fcbef

**Comment by slang25** [comment]
This should be resolved once we get #243 merged and releases 🤞

**Comment by WeihanLi** [comment]
Thanks @slang25 , closing this since it's duplicate of #6
