### ISSUE TITLE
fails when solution contains .sqlproj

### ISSUE THREAD

**Issue by spaasis** [dotnet-outdated/dotnet-outdated#321]
Hi,
Thanks for the great package!

I recently tried to automate nuget updates to a solution that contains a database project. This fails with the standard 

```
Analyzing project(s)...Unable to process the project `D:\a\1\s\Project.sln. Are you sure this is a valid .NET Core or .NET Standard project type?

Here is the full error message returned from the Microsoft Build Engine:

Microsoft (R) Build Engine version 17.2.0+41abc5629 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

D:\a\1\s\src\Infrastructure\SeSuDB\SeSuDB.sqlproj(58,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\6.0.302\Microsoft\VisualStudio\v11.0\SSDT\Microsoft.Data.Tools.Schema.SqlTasks.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\sdk\6.0.302\\Microsoft\VisualStudio\v11.0\SSDT\Microsoft.Data.Tools.Schema.SqlTasks.targets" is correct, and that the file exists on disk.
 -  - exit code: 1

```

More information on the issue:
https://github.com/dotnet/sdk/issues/10441
https://github.com/dotnet/sdk/issues/16587

Possible solution:
Allow us to give -configuration "Release" as parameter for the restore/build commands. Then we could ignore the project from Release config builds which I think would be enough

**Comment by nyiroe** [comment]
A workaround:

https://github.com/dotnet/sdk/issues/10441#issuecomment-584684450

**Comment by spaasis** [comment]
@nyiroe funny enough - I just got this working (by accident) using that. Seems I didn't test it thoroughly enough before creating the issue. Closing 👌
