### ISSUE TITLE
Colors don't work on Azure DevOps 

### ISSUE THREAD

**Issue by andrew-flatters-bliss** [dotnet-outdated/dotnet-outdated#340]
Could be a different mod/ flag to the command as know this won't work for everyone

https://learn.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=powershell#formatting-commands

```
steps:
- bash: |
    echo "##[group]Beginning of a group"
    echo "##[warning]Warning message"
    echo "##[error]Error message"
    echo "##[section]Start of a section"
    echo "##[debug]Debug text"
    echo "##[command]Command-line being run"
    echo "##[endgroup]"
```

Example what it currently outputs like:

![image](https://user-images.githubusercontent.com/63094835/195831114-bc967c38-8131-4c63-a2a6-d984df0ecefc.png)

**Comment by slang25** [comment]
This would be a nice addition, I think adding a new formatter now that this abstraction has been introduced would be the way to go:
#343

**Comment by andrew-flatters-bliss** [comment]
Updating this to using the markdown option but displaying in Pipelines using this extension: [Publish markdown reports](https://marketplace.visualstudio.com/items?itemName=MasamitsuMurase.publish-markdown-reports) as couldn't find any other way to show this up in the pipeline using the markdown: 

Outputted code:

<html>
<body>
<h3 id="targetnet60" style="margin: 0px 0px 8px; padding: 0.875rem 0px 2px; line-height: 1; color: var(--darkreader-text--nc-tx-1); border-bottom: 1px solid var(--darkreader-border--nc-bg-2); font-size: 1.55rem; font-family: Inter, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(0, 0, 0); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Target:net6.0</h3>

Package | Transitive | Current | Last | Severity
-- | -- | -- | -- | --
Microsoft.EntityFrameworkCore | False | 6.0.15 | $\textcolor{red}{\textsf{7.0.0}}$ | Major
Microsoft.EntityFrameworkCore.Cosmos | False | 6.0.15 | $\textcolor{red}{\textsf{7.0.0}}$ | Major

<br class="Apple-interchange-newline">
</body>
</html>

What DevOps shows:

![image](https://user-images.githubusercontent.com/63094835/228839261-6135f1f8-8b9d-4c82-bb96-4b22c996271a.png)


This could be a problem with the Pipeline Extension I am using also.

**Comment by quasarea** [comment]
I'm able to replicate this issue using azure rest api directly, https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull%20request%20thread%20comments?view=azure-devops-rest-6.0

So, it is not fault of the extension you are using, looks like azure markdown does not support colours in PRs.

Would be nice to be able to skip colour generation with a flag, or using colour balls instead, as those are showing up fine
🔴: Major version update or pre-release version. Possible breaking changes.
🟡: Minor version update. Backwards-compatible features added.
🟢: Patch version update. Backwards-compatible bug fixes.
