### ISSUE TITLE
List all packages (including the ones that do not need upgrades)

### ISSUE THREAD

**Issue by gigi81** [dotnet-outdated/dotnet-outdated#344]
Is there an option to list also the packages including the ones that do NOT need to be updated?
I tried with the built-in command
```
dotnet list package --include-transitive --outdated
```
but the output is not as comprehensive as dotnet-outdated as this tool goes deeper in the dependency tree of the transitive dependencies.

**Comment by quasarea** [comment]
This would be really useful, @slang25 would you consider this change?

**Comment by slang25** [comment]
I like this idea, I think it would be a fitting addition.

@gigi81 if you are happy to create a PR from your branch I'll review it from there

**Comment by gigi81** [comment]
Hi @slang25, I pushed the PR above.
I was not sure what to do with the output symbol "->", in the end I replaced it with == when the dependency has no updates.
