### ISSUE TITLE
dotnet_host_path

### ISSUE THREAD

**Issue by doterik** [dotnet-outdated/dotnet-outdated#350]
Version 4.3.1 rendered the following errors:

* Errors occurred while analyzing dependencies for some of your projects. Are you sure you can connect to all your configured NuGet servers?

* Unable to find DOTNET_HOST_PATH environment variable. If you use credential providers for your NuGet sources you need to have this set to the path to the `dotnet` executable.

After setting the environment variable (why do I need to do that..!), the first error still remains.

This worked flawlessly yesterday (no problem if I use  CLI or VS).

**Comment by solrevdev** [comment]
Version 4.3.2 should fix this @doterik

**Comment by doterik** [comment]
👍🏼

**Comment by allensanborn** [comment]
This is happening to me to with version 4.6.4+3bad9cacfd8752a5d0a98fad47493c26bd8f5a88

We use private Nuget feeds that are configured in a repo level nuget.config file.

Is there any useful information that I can provide?

```
Errors occurred while analyzing dependencies for some of your projects. Are you sure you can connect to all your configured NuGet servers?

Unable to find DOTNET_HOST_PATH environment variable. If you use credential providers for your NuGet sources you need to have this set to the path to the `dotnet` executable.
```
