### ISSUE TITLE
Deadlock when using the library

### ISSUE THREAD

**Issue by yenneferofvengerberg** [dotnet-outdated/dotnet-outdated#369]
When using the latest version of the library, sometimes the are deadlocks when running during unit testing.

The issue is due to asynchronous code being locked on the original thread. Using `ConfigureAwait(false)` solves the issue.

**Comment by slang25** [comment]
Thanks @yenneferofvengerberg! I think there is a code analyzer rule we can enable for this to prevent future cases creeping in, I'll look at that separately 🙂

**Comment by yenneferofvengerberg** [comment]
I have fixed those issues (and many others, including code analysis) in another fork (https://github.com/yextly/dotnet-outdated, branch main). How would you like to proceed? Shall I open many PRs or a single one?

**Comment by slang25** [comment]
@yenneferofvengerberg sorry for the slow response, I've had a scan and I like the changes generally. If you are happy to, please open a PR with as many changes as your happy to contribute and I'll prioritise reviewing it.

**Comment by yenneferofvengerberg** [comment]
@slang25 don't worry. I have just backported part (if not all) of what we have in our branch in #382. Hope it helps the library to grow :)
