### ISSUE TITLE
Errors when projects target .NET 5

### ISSUE THREAD

**Issue by augustoproiete** [dotnet-outdated/dotnet-outdated#40]
Reporting this issue for awareness only as this looks like an issue with .NET 5 and not with dotnet-outdated specifically, but anyway:

dotnet-outdated v2.11.0

---

After updating the TFM of my projects to `net5.0` and running `dotnet outdated` the analyze the packages to migrate, I'm getting the errors below:

```
Errors occurred while analyzing dependencies for some of your projects. Are you sure you can connect to all your configured NuGet servers?

Unable to find DOTNET_HOST_PATH environment variable. If you use credential providers for your NuGet sources you need to have this set to the path to the `dotnet` executable.
```

I have a `nuget.config` at the root the repo pointing to nuget.org exclusively thus I don't think it's the case of not being able to connect to nuget servers.

`DOTNET_HOST_PATH` is indeed not defined (not sure why... Probably something missing in the .NET 5 SDK install process).

My `nuget.config`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
  <disabledPackageSources>
    <clear />
  </disabledPackageSources>
  <fallbackPackageFolders>
    <clear />
  </fallbackPackageFolders>
</configuration>
```

**Comment by coderpatros** [comment]
Hi @augustoproiete, are you able to share a csproj file that reproduces this?

**Comment by augustoproiete** [comment]
Hi @coderpatros, yes. After some trial and error I was able to find at least one of the packages causing the error and was able to reproduce in isolation:

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="5.0.0" />
  </ItemGroup>
</Project>
```

![image](https://user-images.githubusercontent.com/177608/98822375-293a7500-2407-11eb-9fbe-ee18088e30ec.png)

**Comment by simplyvinay** [comment]
Ran into the same problem when migrating to .net 5.. 

`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" Version="1.1.0" />
    <PackageReference Include="FluentValidation" Version="9.3.0" />
    <PackageReference Include="MediatR" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="3.1.10" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="4.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="5.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="3.1.4" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.Design" Version="1.1.0" />
  </ItemGroup>
</Project>`

![image](https://user-images.githubusercontent.com/167894/98837242-a4694e80-243a-11eb-9802-308e74f3a845.png)

**Comment by slang25** [comment]
I'm unable to replicate the issue with the csprojs or nuget.config from above. Could you try setting `DOTNET_HOST_PATH` ([see here](https://github.com/dotnet/sdk/issues/14497#issuecomment-725454341)) and see if that works around this issue?

**Comment by simplyvinay** [comment]
> I'm unable to replicate the issue with the csprojs or nuget.config from above. Could you try setting `DOTNET_HOST_PATH` ([see here](https://github.com/dotnet/sdk/issues/14497#issuecomment-725454341)) and see if that works around this issue?

Adding the setting to the env variables fixed the error from the missing variable but not the error from nuget

![image](https://user-images.githubusercontent.com/167894/98842337-53108d80-2441-11eb-8cde-9b693344d69b.png)

here is my nuget.config

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <activePackageSource>
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </activePackageSource>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
```

**Comment by augustoproiete** [comment]
> Adding the setting to the env variables fixed the error from the missing variable but not the error from nuget

Same for me.

**Comment by coderpatros** [comment]
@augustoproiete and @simplyvinay, can you please let me know what OS you are using and the output of `dotnet --list-sdks`

I can't locally reproduce this either :(

**Comment by augustoproiete** [comment]
@coderpatros I can reliably reproduce this in two separate Windows 10 machines.

![image](https://user-images.githubusercontent.com/177608/98863792-42f7ae80-243f-11eb-99dd-d326b841de68.png)

```
C:\>dotnet --list-sdks
2.1.801 [C:\Program Files\dotnet\sdk]
2.1.802 [C:\Program Files\dotnet\sdk]
2.2.401 [C:\Program Files\dotnet\sdk]
3.1.101 [C:\Program Files\dotnet\sdk]
3.1.102 [C:\Program Files\dotnet\sdk]
3.1.302 [C:\Program Files\dotnet\sdk]
5.0.100 [C:\Program Files\dotnet\sdk]
```

**Comment by slang25** [comment]
🤔  Could someone please share their output of `dotnet nuget list source`

**Comment by augustoproiete** [comment]
```
C:\augustoproiete>dotnet nuget list source
Registered Sources:
  1.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json

C:\augustoproiete>
```

**Comment by slang25** [comment]
Thanks @augustoproiete 😃, for comparison mine is:
```
Registered Sources:
  1.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
  2.  Microsoft Visual Studio Offline Packages [Enabled]
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
```
I'll disable the offline cache and see if I get the same 🤞

**Comment by slang25** [comment]
Ah! Ok, the penny has dropped.

So when you run `dotnet outdated --version` you see `2.11....`, this is the original tool that was abandoned and de-listed from nuget.org.

This repository is the official continuation of that project, however has a different nuget id.

In order to have the latest version which should not have this issue please run the following:
```
dotnet tool uninstall --global dotnet-outdated
dotnet tool install --global dotnet-outdated-tool
```

As a consumer of this tool, this sucks, please accept my appologies. If you still have this issue then please let us know.

**Comment by augustoproiete** [comment]
@slang25 Ah, perfect! That explains it. Uninstalling the _outdated_ `dotnet-outdated` :smile:  and installing the new one resolved the issue. Thank you so much for the help troubleshooting it!

_ps: As a suggestion, it would be nice if @jerriep could transfer the ownership of the old nuget package to the `dotnet-outdated` organization on nuget.org to allow you to do one last release of a tool that just prints the instructions above on the Console to guide devs on moving to the new one_.

**Comment by coderpatros** [comment]
@augustoproiete I agree it's not a great migration for existing users. But Jerrie was done.

Unfortunately the NuGet tooling doesn't have a good mechanism to handle this situation.

I am glad that Jerrie didn't hand over control of the package to someone. They could have just as easily dropped a shell or harvest credentials as much as they could have maintained it like we are.

**Comment by slang25** [comment]
Yeah, I did have a chat with Jerrie about it, but he had security concerns. He can never truly be free of it any other way. I appreciate it's not ideal for existing users, but I respect his call, we owe it to him to let the existing package be.

**Comment by weitzhandler** [comment]
I just installed outdated for the first time. When running it I still got that error, but it might had to do with dependencies on old preview .NET versions, once I hard-reset master to upstream it worked fine.

**Comment by coderpatros** [comment]
I've also just release a new version, 3.1.0, that targets .NET 5. That might also be a confounding factor. But if you have any more issues @weitzhandler please raise an issue.

**Comment by snow-jallen** [comment]
I'm running 3.1.0 and I'm getting that same "Errors occurred while analyzing dependencies for some of your projects.  Are you sure you can connect to all your configured NuGet servers?" error. :-(

```
❯ dotnet nuget list source
Registered Sources:
  1.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
  2.  Microsoft Visual Studio Offline Packages [Enabled]
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\


❯ type .\HomeSpeaker.Web\HomeSpeaker.Web.csproj
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <UserSecretsId>aspnet-HomeSpeaker.Web-8CE5379C-7C29-4A6C-8833-2E36F9D506F3</UserSecretsId>
    <CopyRefAssembliesToPublishDirectory>false</CopyRefAssembliesToPublishDirectory>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibVLCSharp" Version="3.4.9" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="5.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="5.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="5.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="5.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="5.0.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.10.9" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.11" />
    <PackageReference Include="Vlc.DotNet.Core" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HomeSpeaker.Lib\HomeSpeaker.Lib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\" />
  </ItemGroup>

</Project>

❯ dotnet outdated --version
A .NET Core global tool to list outdated Nuget packages.
3.1.0

❯ dotnet --list-sdks
5.0.100 [C:\Program Files\dotnet\sdk]

```

:-( Any suggestions?

**Comment by tjrobinson** [comment]
I had the same issue just now (everything up to date as described above) and, for me, the fix was to remove the reference to:

```
<PackageReference Include="ReSharper.Annotations" Version="7.1.3.130415" />
```

Looking at the [NuGet Gallery](https://www.nuget.org/packages/ReSharper.Annotations/), this package has a note saying _"This package has been deprecated as it is legacy and is no longer maintained."_ and for [the specific version I was referencing](https://www.nuget.org/packages/ReSharper.Annotations/7.1.3.130415), it's been delisted - _"The owner has unlisted this package. This could mean that the package is deprecated, has security vulnerabilities or shouldn't be used anymore."_

**So my theory is that `dotnet-outdated` fails if a package has been delisted?**

**Comment by VahidN** [comment]
It's happening again with .NET 7.0 RTM.

**Comment by slang25** [comment]
I'm debugging it here, will release a reverted 4.3.1 for now...

**Comment by hackf5** [comment]
v4.3.1 and v4.3.0 both seem to have issues with .NET 7, reverting to v4.2.0 seems to be a temporary workaround.

**Comment by hackf5** [comment]
@slang25 all good now on 4.3.2. thanks for the quick update!

**Comment by jonassamuelssoncab** [comment]
I'm still seeing this in v4.3.2.
![image](https://user-images.githubusercontent.com/91466748/201345887-34311c3c-f260-44a3-a3bc-eb5277523d4d.png)

If I run against a project that only has dependencies from nuget.org it works fine.
![image](https://user-images.githubusercontent.com/91466748/201345990-9ba74b2a-b9a1-4a18-9dca-6aab229e5285.png)

If I run against a project with dependencies from our private azure devops feed it fails.
![image](https://user-images.githubusercontent.com/91466748/201346136-4b8244cc-0fdc-4857-a027-6337c8ba44e9.png)

Deleting bin & obj folders, then `dotnet restore --force --no-cache` works fine, same for updating packages via VS UI.

**Comment by jonassamuelssoncab** [comment]
I have now done som emore investigations and solved the problem, this is how.

When running `dotnet list package --outdated` I got the following warning
_The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet`_.

After running `dotnet list package --outdated --interactive` and logging in, `dotnet-outdated` started worked again.

If possible, it would be nice if dotnet-outdated could surface this information to me in some way.
