### ISSUE TITLE
Auto-update outdated packages

### ISSUE THREAD

**Issue by VladislavAntonyuk** [dotnet-outdated/dotnet-outdated#43]
Add new args to allow automatically update outdated packages
-u|--upgrade -> update all packages to the latest version (stable) - already exists
--update-major -> update all packages to the latest major version (stable)
--update-preview - > update all packages to the latest version (preview)

**Comment by coderpatros** [comment]
Hi @VladislavAntonyuk 

There is already a `--pre-release` parameter that enables updating to preview versions. The default is to only use new preview versions if the reference is already to a preview version.

There is also a `--version-lock` parameter that can be used to fix versions to either major or minor releases. For example if you use major as the version lock, and have a reference to version 1.0.0 it will look for the latest 1.x.x release.

**Comment by VladislavAntonyuk** [comment]
Thank you @coderpatros. I think I can close it
