### ISSUE TITLE
Unable to run dotnet outdated inside docker

### ISSUE THREAD

**Issue by moni-dips** [dotnet-outdated/dotnet-outdated#432]
When I try to run dotnet outdated inside a dotnet 7 docker image, I get this error:

```
You must install or update .NET to run this application.

App: /root/.nuget/packages/dotnet-outdated/2.11.0/tools/netcoreapp3.0/any/dotnet-outdated.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '3.0.0' (x64)
.NET location: /usr/share/dotnet/

The following frameworks were found:
  7.0.5 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.0.0&arch=x64&rid=debian.11-x64
```

The tool is installed as a local dotnet tool and restored from the tool manifest as part of the build process.

**Comment by slang25** [comment]
The path above mentions dotnet-outdated `2.11.0`, this is likely from the very old deprecated version that [now lives here](https://www.nuget.org/packages/coderpatros-dotnet-outdated).
Could you try [the latest version](https://www.nuget.org/packages/dotnet-outdated-tool) and see how you get on.

**Comment by moni-dips** [comment]
Ah! That makes a lot of sense, thank you!
