### ISSUE TITLE
Doesn't work with Xamarin projects

### ISSUE THREAD

**Issue by VladislavAntonyuk** [dotnet-outdated/dotnet-outdated#44]
Unable to process the project `Test.sln. Are you sure this is a valid .NET Core or .NET Standard project type?
Here is the full error message returned from the Microsoft Build Engine:

Microsoft (R) Build Engine version 16.8.0-preview-20464-02+0220c5eae for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

Android.csproj(124,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\6.0.100-alpha.1.20467.1\Xamarin\Android\Xamarin.Android.CSharp.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\sdk\6.0.100-alpha.1.20467.1\\Xamarin\Android\Xamarin.Android.CSharp.targets" is correct, and that the file exists on disk.
iOS.csproj(137,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\6.0.100-alpha.1.20467.1\Xamarin\iOS\Xamarin.iOS.CSharp.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\sdk\6.0.100-alpha.1.20467.1\\Xamarin\iOS\Xamarin.iOS.CSharp.targets" is correct, and that the file exists on disk.
 -  - exit code: 1

**Comment by coderpatros** [comment]
Hi @VladislavAntonyuk, I haven't done any Xamarin myself. Just to rule out the basics, you have confirmed those files do exist?

**Comment by VladislavAntonyuk** [comment]
hmm, looks like it is an dotnet issue. it doesn't work with Xamarin. If I manually copy the folder to the target location it works.

**Comment by winstonpang** [comment]
@VladislavAntonyuk Just wondering so you did it get it to work? What folder did you copy to which target location? Thanks.

**Comment by VladislavAntonyuk** [comment]
From visual studio msbuild folder to dotnet sdk

**Comment by winstonpang** [comment]
As in those targets are copied over, does it work after that?

**Comment by VladislavAntonyuk** [comment]
You can see in the description all the files which are missed. It you copy them it works as expected

**Comment by winstonpang** [comment]
Great, I tried what you suggested and it works flawlessly, thanks!

**Comment by VladislavAntonyuk** [comment]
@winstonpang just a note. if you are using CI this folder doesn't exist, so it will work only on your local environment
