### ISSUE TITLE
Error sometimes when first run

### ISSUE THREAD

**Issue by WeihanLi** [dotnet-outdated/dotnet-outdated#463]
Sometimes I get error when running `dotnet-outdated`, while when I try again, it success, nothing changes

![image](https://github.com/dotnet-outdated/dotnet-outdated/assets/7604648/062b94f9-02fa-478d-b09d-f63443e66376)

**Comment by reduckted** [comment]
This sounds like a duplicate of #251 - the `dotnet restore` step takes "too long" and `dotnet-outdated` aborts.
