### ISSUE TITLE
PackageReference duplication

### ISSUE THREAD

**Issue by fubar-coder** [dotnet-outdated/dotnet-outdated#503]
I have the problem that I get duplicated PackageReference entries in my project.

Steps to reproduce:

- Reconfigure Visual Studio 2022 to use PackageReference for non-SDK projects
- Create a .NET Framework Class Library project
- Add a package (e.g. System.Net.Http.Json version 7.0.1)
- Execute `dotnet outdated -u`

This keeps the original PackageReference and adds the new PackageReference.

**Comment by Banner-Keith** [comment]
I am also dealing with this issue.

**Comment by FXZFun** [comment]
I would also like to see this implemented in the next release, the necessary changes for this issue already exists in #242. I am using a version built from the source with these changes with no issues.
