### ISSUE TITLE
How about an option to flag security issues against sonatype?

### ISSUE THREAD

**Issue by alastairtree** [dotnet-outdated/dotnet-outdated#54]
Great tool, thanks!

This is a feature suggestion/discussion. There is another similar tool at https://github.com/fabiano/dotnet-ossindex which checks the sonatype API (which is free) for packagaes which have known security issues published but I think it would be great if it was incorporated into dotnet-outdated so users  can do outdated packages and security issues in one sweep. How about adding a flag like `--security`  which also checks all packages with for known CVEs security issues listed in sonatype as well and flags these prominently in the output/return code?

**Comment by coderpatros** [comment]
Hi @alastairtree I don't think I would implement this myself. But I really like the idea.

**Comment by augustoproiete** [comment]
I personally think it's not a good idea for a couple of reasons:

#### 1. Do one thing, and do it well
In my view, a dotnet tool should be small, do one thing, and do it well. `dotnet-outdated` specializes in detecting dependencies that can be updated, and update them for you if you wish... That's it! :smile:

If I wanted to check for security issues through the Sonatype API I'd use a tool that is built for that purpose, such as `dotnet-ossindex` or a similar dotnet tool that specializes in security analysis using the Sonatype API...

If I wanted to run multiple tools often, I'd create a `.cmd` (or `.sh` or `ps1`, etc.) that runs multiple dotnet tools in a sequence... It's as simple as that.

#### 2. There are many other APIs one can use for security analysis ...
... free and commercial, and Sonatype is just one of them.

So after the Sonatype checks are bundled in `dotnet-outdated`, what's next? Should we implement security checks for the Snyk API, Checkmarx API, Black Duck API, etc.? :sweat_smile:

You can probably see how bloated `dotnet-outdated` would become...

**Comment by coderpatros** [comment]
Hi @augustoproiete, those are all valid points. Although I think OSS index is a bit unique in terms of the access and coverage they provide the open source software ecosystem.

On the surface I like the idea of highlighting to a user that one dependency update may be much more important than another one.

But having thought about this some more it's not quite as simple as it seems.

This tool only analyses direct dependencies. Vulnerabilities are often in transitive dependencies. Especially if you are keeping your direct dependencies up to date.

I don't really want to get into that space with this tool. And I'd prefer to show no vulnerability information over giving users known incomplete information like dotnet-ossindex does.

@alastairtree, you really need to be generating a complete software bill of materials to ensure you fully understand the risk from the 3rd party components you are using.
