### ISSUE TITLE
dotnet restore fails if any packages have vulnerabilities

### ISSUE THREAD

**Issue by martincostello** [dotnet-outdated/dotnet-outdated#548]
If `dotnet outdated` is run on a project using a NuGet package that has a known vulnerability, `dotnet restore` will fail due to [NuGet Audit](https://learn.microsoft.com/nuget/concepts/auditing-packages) errors if `TreatWarningsAsErrors=true`.

This is problematic as it prevents the user from using dotnet outdated itself to see what package updates are available that may resolve the problem.

This behaviour can be suppressed by passing `NuGetAudit=false` through to the restore operation. Alternatively, `NU1902` and `NU1903` can be disabled.

**Comment by slang25** [comment]
Very nice, do we know if it's possible to disable warnings as errors completely?
