### ISSUE TITLE
Unable to update packages when NuGet cache is empty

### ISSUE THREAD

**Issue by shivinsky** [dotnet-outdated/dotnet-outdated#55]
Our CI fails to update dependencies from time to time.
Seems like that [20 seconds timeout](https://github.com/dotnet-outdated/dotnet-outdated/blob/cb3da116b4202b0662c088a8870152a06498a40e/src/DotNetOutdated.Core/Services/DotNetRunner.cs#L36) is not enough for a large project with empty `NuGet` cache.
Currently, I don't see any reason to run `MSBuild` with timeout. Any chance to remove it completely?

As a temporary workaround it is possible to run `dotnet restore`  in advance.

**Version used**: 3.0.2

**Steps to reproduce:**
1. Clear NuGet cache `dotnet nuget locals all --clear`
2. Run the tool `dotnet outdated`

**Expected behavior:**
No errors.

**Actual behavior:**
`Are you sure this is a valid .NET Core or .NET Standard project type?`

**Comment by coderpatros** [comment]
Hi @shivinsky I've had this same problem with another tool I maintain. I don't want to remove the timeout completely. Some issues can cause it to hang indefinitely without it.

But 20 seconds is pretty low. I'll increase it and add a parameter that allows overriding the timeout value.

**Comment by ransagy** [comment]
I've opened #248 to make this configurable and increased the default to 30s.
In my case the cache wasn't empty, but the restore op takes a bit longer than 20s with some specific large solutions, but it fits both cases.
